version: "3.8"

services:
  mysql-server:
    image: mysql:8
    container_name: mysqlserver
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=mysqlhexa
    ports:
      - "3310:3306"
    networks:
      - net-mysql
    volumes:
      - vol-mysql:/var/lib/mysql

networks:
  net-mysql:

volumes:
  vol-mysql:
